### ISSUE TITLE
freqlist: noticeably slower when 15+ categories, consider re-working for speed

### ISSUE THREAD

**Issue by sinnweja** [eheinzen/arsenal#20]

**Comment by eheinzen** [comment]
Reproducible example?

**Comment by sinnweja** [comment]
I have a function called resources (adapted from Venebles and Ripley's "S Programming" that essentially does proc.time before and after evalulation, and some operations with gc() before and after.    I make a 16 category data.frame and run freqlist on it with various numbers of the categories to be tabulated in freqlist. The run times increase from 10-14, but doubles in the 14-16 variable size.
R> dfcats <- matrix(rbinom(160, size=2, prob=.2), ncol=16)
R> dim(dfcats)
[1] 10 16
R> colnames(dfcats) <- paste0("c", 1:16)
R> dfcats[1:2,]
     c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16
[1,]  0  0  0  0  0  0  0  0  2   1   0   1   1   0   0   0
[2,]  0  0  0  0  1  0  0  1  1   0   0   2   2   0   1   0
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 2.315   2.315     100     0    224
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 2.236   2.236     100     0     40
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 7.755   7.755     100     0    333
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 7.916   7.916     100     0     40
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16)))})
          CPU Elapsed CPU.pct Child Vcells
user.self 7.5     7.5     100     0     40
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 3.026   3.026     100     0     14
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 2.847   2.847     100     0     40
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.479   1.479     100     0    -12
R> resources({flcats <- with(as.data.frame(dfcats), freqlist(table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10)))})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.568   1.568     100     0     40

**Comment by sinnweja** [comment]
It appears that a solid (consistent) chunk of the time is used by the table function in my example, but it does not account for the jump in time for freqlist on pre-computed table() results. Some initial thoughts are that the apply() on the is.na could be taking some time. We could delay the rounding of digits until the very end. Nothing else is jumping out at me without profiling the code.
R> resources({fltab16 <- with(as.data.frame(dfcats), table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16))})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.058   1.058     100     0 280025
R> resources({fltab14 <- with(as.data.frame(dfcats), table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14))})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.433   1.433     100     0  70066
R> resources({fltab10 <- with(as.data.frame(dfcats), table(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10))})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.382   1.382     100     0   2053
R> resources({flcat10 <- freqlist(fltab10)})
            CPU Elapsed CPU.pct Child Vcells
user.self 1.514   1.514     100     0    141
R> resources({flcat14 <- freqlist(fltab14)})
            CPU Elapsed CPU.pct Child Vcells
user.self 3.411   3.411     100     0    272
R> resources({flcat16 <- freqlist(fltab16)})
            CPU Elapsed CPU.pct Child Vcells
user.self 8.336   8.336     100     0    333

**Comment by eheinzen** [comment]
(Edited your comments to make the code more readable)
