### ISSUE TITLE
Preserving control parameters before merge

### ISSUE THREAD

**Issue by dchiu911** [eheinzen/arsenal#217]
A merged `arsenal_table` object inherits `tableby.control` parameters from the first table. How can I preserve the parameters from before the merge, such that `tab1` can be rounded to 0 digits and `tab2` can be rounded to 1 digits?

Right now, for
```r
tab12 <- merge(tab1, tab2)
```
`tab12` rounds to 0 (first table)

**Comment by eheinzen** [comment]
Sorry it took so long to get back to you.  I have a few ideas for a workaround:

```
library(arsenal)
data(mockstudy)

tab1 <- tableby(sex ~ age, data = mockstudy)
tab2 <- tableby(sex ~ ps + fu.stat, data = mockstudy, digits = 0)

# this doesn't work, as you noted
summary(merge(tab1, tab2))

vars <- c("ps", "fu.stat")
tab3 <- tableby(formulize("sex", paste0("anova(", vars, ", digits = 0)")), data = mockstudy)

# this also doesn't work... I'm planning to fix this
summary(merge(tab1, tab3))

# but this does
summary(merge(tab3, tab1))


# so does this, by some miracle
out <- list(rbind(
  as.data.frame(summary(tab1)),
  as.data.frame(summary(tab2))
))
class(out) <- c("summary.arsenal_table", "data.frame")
out
```

**Comment by eheinzen** [comment]
I've fixed

```
summary(merge(tab1, tab3))
```

in #221.

The `arsenal_table` objects weren't really designed to hold more than one control list, so we rely on in-formula specification to change individual terms (that's what the `formulize()` call above is doing).
