### ISSUE TITLE
tabby summary output pdf for big table

### ISSUE THREAD

**Issue by kanazawahere** [eheinzen/arsenal#224]
I want them to fit the width of my page. But I don't know how to do that. Please help

<img width="589" alt="Screen Shot 2019-06-15 at 15 51 42" src="https://user-images.githubusercontent.com/50522881/59548150-8b2e4b00-8f85-11e9-808e-1473d2d2a367.png">

**Comment by eheinzen** [comment]
This is really a problem for `knitr::kable()`, but I have two ideas to help:

1. Use the `width=` argument to `print()`:

```
> print(summary(tableby(sex ~ age, data = mockstudy),
                labelTranslations = list(age = "A really long label"), text = TRUE), width = 10)


|             |  Male (N=916)   | Female (N=583)  | Total (N=1499)  | p value|
|:------------|:---------------:|:---------------:|:---------------:|-------:|
|A really     |                 |                 |                 |   0.048|
|long label   |                 |                 |                 |        |
|-  Mean (SD) | 60.455 (11.369) | 59.247 (11.722) | 59.985 (11.519) |        |
|-  Range     | 19.000 - 88.000 | 22.000 - 88.000 | 19.000 - 88.000 |        |

```

2. Use a different format in `print()`, e.g. pandoc:

```
> print(summary(tableby(sex ~ age, data = mockstudy),
                labelTranslations = list(age = "A really long label"), text = TRUE), format = "pandoc")


                        Male (N=916)      Female (N=583)     Total (N=1499)     p value
--------------------  -----------------  -----------------  -----------------  --------
A really long label                                                               0.048
-  Mean (SD)           60.455 (11.369)    59.247 (11.722)    59.985 (11.519)           
-  Range               19.000 - 88.000    22.000 - 88.000    19.000 - 88.000           

```

**Comment by kanazawahere** [comment]
I got the table fit in page, but the variable name is wrapped, it is not easy to read and so many spaces are wasted, can I change it to something like overflow 


<img width="520" alt="Screen Shot 2019-06-19 at 23 27 03" src="https://user-images.githubusercontent.com/50522881/59774065-c31cf180-92e9-11e9-9c1f-64def1537cbd.png">

<img width="358" alt="Screen Shot 2019-06-19 at 23 31 47" src="https://user-images.githubusercontent.com/50522881/59774444-6a9a2400-92ea-11e9-9e5d-d5f4eca2d154.png">

**Comment by eheinzen** [comment]
That would be something for rmarkdown, knitr, or pandoc instead of the arsenal package.  Sorry I can't be more helpful!

**Comment by dchiu911** [comment]
Hi @kanazawahere 

You can pass `arsenal:::summary.tableby()` to `knitr::kable()` then play around with `kableExtra` options such as scaling down the table:
```r
# arsenal only
tab %>%
  summary(labelTranslations = labels, title = "(#tab:chunk-label) Caption")

# arsenal, kable, and kableExtra
tab %>%
  summary(labelTranslations = labels) %>%
  as.data.frame() %>%
  knitr::kable(caption = "Caption", format = "latex", escape = FALSE) %>% 
  kableExtra::kable_styling(latex_options = "scale_down")
```
