### ISSUE TITLE
issue with: modelsum binomial ~ with categorical variable

### ISSUE THREAD

**Issue by kanazawahere** [eheinzen/arsenal#225]
Variable gender have male and female, but the table only calculate for male. I dont know what is wrong
<img width="859" alt="Screen Shot 2019-06-19 at 23 11 21" src="https://user-images.githubusercontent.com/50522881/59773127-0d9d6e80-92e8-11e9-8aec-87d55e6aaeb9.png">
<img width="329" alt="Screen Shot 2019-06-19 at 23 22 23" src="https://user-images.githubusercontent.com/50522881/59773753-26f2ea80-92e9-11e9-98a2-128c54859d87.png">

**Comment by eheinzen** [comment]
This is to be expected.  With modeling in R (including `modelsum()`), the first level of a factor (or character for that matter) is used as the reference level.  In other words, "gender" becomes a 0/1 variable with 0 indicating female and 1 indicating male.  You then model the increase from female to male (i.e., from 0 to 1).

This happens in base R.  For example, here "male" is taken to be the reference level:

```
> library(arsenal)
> data(mockstudy)
> summary(glm(fu.stat == 2 ~ sex, data = mockstudy, family = "binomial"))

Call:
glm(formula = fu.stat == 2 ~ sex, family = "binomial", data = mockstudy)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.1698   0.4468   0.4468   0.4494   0.4494  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  2.25431    0.11270  20.003   <2e-16 ***
sexFemale   -0.01246    0.18015  -0.069    0.945    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 943.92  on 1498  degrees of freedom
Residual deviance: 943.91  on 1497  degrees of freedom
AIC: 947.91

Number of Fisher Scoring iterations: 5
```
