### ISSUE TITLE
summary statistics per factor

### ISSUE THREAD

**Issue by MarcoHelbich** [eheinzen/arsenal#237]
How can I get a summary statistic for a factor referring to a grouped continuous variable? For example, the mean and SD per factor group? 

`
library(arsenal)
dat <- data.frame(x=rnorm(20), y=as.factor((rep(c(1,2), 10))))
ctr <- tableby.control(numeric.stats = c("meansd"), cat.stats = c("countpct"))
tab <- tableby(~ x + y, dat, control=ctr)
summary(tab, text=T)

by(dat$x, dat$y, mean)`

Many thanks in advance! Marco

**Comment by eheinzen** [comment]
Sure thing!  There are two ways to do this:

```
> summary(tableby(y ~ x, data = dat, control = ctr))


|                            |    1 (N=10)    |    2 (N=10)    |  Total (N=20)  | p value|
|:---------------------------|:--------------:|:--------------:|:--------------:|-------:|
|**x**                       |                |                |                |   0.772|
|&nbsp;&nbsp;&nbsp;Mean (SD) | -0.342 (0.822) | -0.216 (1.070) | -0.279 (0.931) |        |

> summary(tableby(~ x, data = dat, control = ctr, strata = y, numeric.simplify = TRUE))


|y  |      | Overall (N=20) |
|:--|:-----|:--------------:|
|1  |**x** | -0.342 (0.822) |
|2  |**x** | -0.216 (1.070) |
```

I hope that helps?
