### ISSUE TITLE
Missing count not displayed with countrowpct

### ISSUE THREAD

**Issue by yoursdearboy** [eheinzen/arsenal#247]
If call `tableby` with `cat.stats = 'countrowpct'`, then arsenal don't show a row with number of missing values. Don't known if it is intended, but anyway this row is very useful.

```r
library(arsenal)

data <- data.frame(x = sample(c('Yes', 'No'), 100, replace = T),
                   y = sample(c('Red', 'Green', 'Blue'), 100, replace = T))
data[sample(1:100, 10), 'y'] <- NA
```

```r
summary(tableby(x ~ y, data))
```

|                         | No (N=48)  | Yes (N=52) | Total (N=100) | p value|
|:------------------------|:----------:|:----------:|:-------------:|-------:|
|**y**                    |            |            |               |   0.550|
|&nbsp;&nbsp;&nbsp;N-Miss |     2      |     8      |      10       |        |
|&nbsp;&nbsp;&nbsp;Blue   | 14 (30.4%) | 18 (40.9%) |  32 (35.6%)   |        |
|&nbsp;&nbsp;&nbsp;Green  | 15 (32.6%) | 11 (25.0%) |  26 (28.9%)   |        |
|&nbsp;&nbsp;&nbsp;Red    | 17 (37.0%) | 15 (34.1%) |  32 (35.6%)   |        |

```r
summary(tableby(x ~ y, data, cat.stats = 'countrowpct'))
```

|                        | No (N=48)  | Yes (N=52) | Total (N=100) | p value|
|:-----------------------|:----------:|:----------:|:-------------:|-------:|
|**y**                   |            |            |               |   0.550|
|&nbsp;&nbsp;&nbsp;Blue  | 14 (43.8%) | 18 (56.2%) |  32 (100.0%)  |        |
|&nbsp;&nbsp;&nbsp;Green | 15 (57.7%) | 11 (42.3%) |  26 (100.0%)  |        |
|&nbsp;&nbsp;&nbsp;Red   | 17 (53.1%) | 15 (46.9%) |  32 (100.0%)  |        |

**Comment by eheinzen** [comment]
Thanks for the example!

The "N-miss" row is a separate stat function from the countpct or the countrowpct.  So try this:

```
summary(tableby(x ~ y, data, cat.stats = c('Nmiss', 'countrowpct')))
```

**Comment by yoursdearboy** [comment]
Oh! I've missed that `cat.stats = 'countrowpct'` changes whole stats, not margin for percents. Cool, thank you.
