### ISSUE TITLE
tableby: options for column headers

### ISSUE THREAD

**Issue by mpru** [eheinzen/arsenal#256]
It would be nice to make it an option to include or not the counts in the column headers: "(N=...)". Also, when there's no lhs in the formula, the column's header is set to "Overall" and it would also be nice if one could choose which title to use.
By the way, tableby is a super useful tool, thanks!

**Comment by eheinzen** [comment]
Excellent ideas.

The first has a hack in #36, but I'd like to make that more formal.
The second is fixed in #253, which hasn't been rolled out to CRAN yet--you can `devtools::install_github("eheinzen/arsenal")` to get the latest version

**Comment by mpru** [comment]
Great!! Thanks!
