### ISSUE TITLE
Pairwise comparisons /post-hoc tests

### ISSUE THREAD

**Issue by lucavd** [eheinzen/arsenal#264]
Hi, first of all thank you for the great package!

I was wondering if it is could be useful to add a built in function to perform pairwise comparisons/post-hoc (and subsequent Tukey, Dunn or Games-Howell adjustments) when ANOVA or Kruskal-Wallis (groups>2) are performed. 

Something as done by the `compareGroups` package that gives a _p overall_ (like already done by your package) but also al **between-groups p** adjusted with the preferred method

``` {r}
library(compareGroups) 
table <- compareGroups(cylinder ~ ., data = mtcars)
pvals <- getResults(table, "p.overall")
p.adjust(pvals, method = "BH")
export_table <- createTable(table)export2word(export_table, file = "table.docx")
``` 

<img width="374" alt="Screen-Shot-2018-08-10-at-4 20 02-PM" src="https://user-images.githubusercontent.com/7904152/70322528-9d00f480-182a-11ea-9a6e-55226674a070.png">

Thank you! # #

**Comment by eheinzen** [comment]
Two thoughts:

1. The post-hoc tests I commented on in #226; it's not really within the scope of tableby to do this.

2. The adjustment for multiple tests _can_ be done, however, using `padjust()` (note the missing dot--this is a method defined in `arsenal`)
