### ISSUE TITLE
comparedf - independent tolerances for each field

### ISSUE THREAD

**Issue by jgilfillan** [eheinzen/arsenal#270]
First of all, great package - especially the comparedf function.
Can you please consider enabling support for individual tolerances for each field. Eg. for some numeric fields, a tolerances of +- 1 is acceptable, while another numeric field might have a tolerances of +-10. This would be very useful.

**Comment by eheinzen** [comment]
Great, glad you like it!

Individual tolerances are supported in the development version (on Github).  It will be published to CRAN as soon as the maintainers return from holiday.  Feel free to try `devtools::install_github("eheinzen/arsenal")` in the meantime.

cc #167
