### ISSUE TITLE
tableby: NaN Standard deviation when there is only one observation

### ISSUE THREAD

**Issue by farhadsalimi** [eheinzen/arsenal#276]
Currently tableby gives NaN if there is only one observation for a category.
It may be better to just give mean when meansd is used rather than giving something like: 22(NaN)

**Comment by eheinzen** [comment]
Just to be certain we're on the same page, it should return NA, not NaN.

I think I'm going to keep that behavior as-is.  It's helpful for people to see those sorts of abnormalities in their data, instead of hiding them by producing different output.  Thoughts?

**Comment by farhadsalimi** [comment]
It used to give me NaN a few times but it should have been unrelated to arsenal. It is giving NA now. :)
I agree that it is useful to have this functionality kept as default but would have been useful if we had an option to replace Na with an optional character ("-" for instance) if NA happened for any reason. I am sure that so many people (including myself :)) use arsenal to generate reports using Rmarkdown and clients usually prefer to have no NAs in their reports!
