### ISSUE TITLE
Write.csv fails for tableby (including vignette example)

### ISSUE THREAD

**Issue by djhejna** [eheinzen/arsenal#278]
It it non-obvious why a user cannot follow the example in the vignette to export the output of tableby to a .csv file.  With some investigating the issue is that as.data.frame() leaves lists in many column entries which write.csv cannot handle.  For a new user of the package the following error is cryptic and the work arounds: breaking up the list into columns is not obvious.  The vignette for tableby appears to have not been run.  It references "tmp" which is not a defined object in the example (copied from modelsum example perhaps).  The real issue is that work arounds are complex, unsatisfying and basically drive users away from using the package and back to home-grown solutions which wastes efficiency:
1) adjusting all output defaults to have single numbers (using mean instead of meansd, and eliminating range and %-ages, or writing custom functions like min, max each on single lines) takes quite a bit of work and makes the output less usable and concise.  
2) unlisting each column generates skewed answers with no header for that column:
mean(sd)     | 110 (4.5) |     becomes     mean(sd) | 110 |  (4.5) |   # and one still has to deal with ()'s
 A simple solution would be to put all "list entries" on their own lines:
mean | 110
sd  | 4.5
range,min | 93
range,max | 108

If there is a magic flag to solve this problem and export using write.csv, I'd be delighted to help with documenting it.  In the mean time the work arounds I have tried aren't really worth documenting.

tab1 <- tableby(arm~sex+age, data=mockstudy)
tab1_df <- as.data.frame(tab1)
write.csv(tab1_df, "testtablewrite.csv")
Error in write.table(tab1_df, "testtablewrite.csv", col.names = NA, sep = ",",  : 
  unimplemented type 'list' in 'EncodeElement'

**Comment by eheinzen** [comment]
You are absolutely right--I'm so sorry about that.  The update in arsenal v1.0.0 (a long time ago--eek!) broke that part of the vignette, but it never got noticed because (as you note) the write.csv command is commented out.

The trick is to `write.csv(as.data.frame(summary(tableby(...))))`.  The `as.data.frame()` method for the *summary* object is what replaces all the list-columns with their pretty-formatted columns.

I have updated the vignettes accordingly.
