### ISSUE TITLE
Formats do not get passed to numbers when using custom stats

### ISSUE THREAD

**Issue by matthewrspiegel** [eheinzen/arsenal#283]
When using a user defined statistic (comma_means for example), arguments for formats, such as digits,  do not get applied to the values. I'm assuming values are calculated in the stats functions first and then formats are applied so this might be tricky with a user defined function that converts the values into character (comma_means). However, for functions like meansd, medianrange, etc. the digit formatting must occur first before concatenation so I'm assuming there would be a way.

**Comment by eheinzen** [comment]
You'll want to use `as.tbstat()` or `as.countpct()` to get custom stats to pick up on the `digits=`, `digits.count=`, and/or `digits.pct=` arguments.  I just added a few more examples to the tableby vignette (see the commit that's linked to this issue), so hopefully those help.
