### ISSUE TITLE
Additional Surv summaries in tableby

### ISSUE THREAD

**Issue by ecpolley** [eheinzen/arsenal#32]
Where in the code would I look if I wanted to extend time-to-event summaries in `tableby` to include a summary of the follow-up time.

    library(survival)
    library(arsenal)
    tab <- tableby(rx ~ Surv(futime, fustat), data = ovarian)
    summary(tab, text = TRUE)

    # also add follow-up time using censoring distribution, so extract the median by group, plus min and max time as a by group summary.
    survfit(Surv(futime, fustat != 1) ~ rx, data = ovarian)

**Comment by eheinzen** [comment]
I didn't do this correctly--reopening.
