### ISSUE TITLE
Better Error Messaging for as.data.frame(summary.tableby)

### ISSUE THREAD

**Issue by btbroderick** [eheinzen/arsenal#75]
For those of us that used to use this method, it would be nice if I got an error message saying that I can't do that in 1,0.0.  Either that or write an S3 method that matches the old way of doing it. I support the latter.

```
library(arsenal)
data("mockstudy")
x <- as.data.frame(summary(tableby(ps ~ sex + age, data = mockstudy)))
```
```
Error in as.data.frame.default(summary(tableby(ps ~ sex + age, data = mockstudy))) : 
  cannot coerce class ""summary.tableby"" to a data.frame
```

**Comment by eheinzen** [comment]
Yep!  This has been completed already (see #60 ).  It should be available on CRAN within a week or two, I hope
